### ISSUE TITLE
Phrase Sentiment Analysis incorrectly labeling IBM alchemy as positive

### ISSUE THREAD

**Issue by JulianNorton** [a16z/ai#79]
# Phrase Sentiment Analysis incorrectly labeling IBM alchemy as positive

![screen shot 2017-06-29 at 5 03 01 pm](https://user-images.githubusercontent.com/2412992/27710202-daccbc8c-5cec-11e7-9bf4-ecfd2e3e2249.png)

The result is `"score": "-0.952903",` which is very negative, but the website result is displaying "Very positive".

Applicable code: 
https://github.com/a16z/ai/blob/77858c8da63250a64065d77edf1138a53e337476/lib/sentiment-analysis.js#L42

**Comment by diegodoval** [comment]
Thanks for the report -- This was a bug in the IBM API that we were circumventing by modifying the value depending on the label, and now they are correctly returning negatives so our workaround breaks :). Fixing now.
